version: '3.8'

services:
  php:
    build:
      context: .
      args:
        - PHP_VERSION=${PHP_VERSION}
    container_name: php
    volumes:
      - .:/srv/web
    environment:
      - XDEBUG_MODE=off
    ports:
      - "9000:9000"
